name: Publish implementation report

on:
  push:
    branches:
      - gh-pages
    paths:
      - reports/implementation.html
  pull_request:
    paths:
      - reports/implementation.html

jobs:
  generate-report:
    name: Generate implementation report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: reports/implementation.html
          TOOLCHAIN: respec
          VALIDATE_LINKS: false
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-device-apis/2021May/0008.html
