name: Publish implementation report

on:
  push:
    branches:
      - gh-pages
    paths:
      - reports/implementation-respec.html

jobs:
  generate-report:
    name: Generate implementation report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: reports/implementation-respec.html
          TOOLCHAIN: respec
          DESTINATION: reports/implementation.html
